FROM nginx:alpine

COPY ./mf_drawer /usr/share/nginx/html/mf_drawer
COPY ./mf_videos /usr/share/nginx/html/mf_videos
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./assets/images /usr/share/nginx/html/assets/images
